# config/packages/doctrine_migrations.yaml
doctrine_migrations:
  dir_name: '%kernel.project_dir%/src/Migrations'
  name: 'Application Migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
  namespace: DoctrineMigrations

  # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
  organize_migrations: BY_YEAR_AND_MONTH

  # Path to your custom migrations template
  custom_template: ~

  # Run all migrations in a transaction.
  all_or_nothing: true